### PR TITLE
BasePage of "MeetSky" project has been created.

### PR DESCRIPTION
**Pull request by ARIKBOGA**
We can use this page and its WebElements by creating an object inside of our own pages classes. Because these WebElements exist on the top menu of all page of our project

### CODE REVIEW

**Review by SerpilOzulu — APPROVED** [review]
you never tire us, you did all of them by yourself, thanks :)

**Comment by rnkaya** [comment]
Thank you. It looks very nice and comprehensive.

**Comment by ARIKBOGA** [comment]
If you finished the review you also can approve it then if everything is OK. @nhlmk @SerpilOzulu

**Review by rnkaya — APPROVED** [review]

**Review by SerpilOzulu — APPROVED** [review]

**Review by ecnracr — COMMENTED** [review]
Wouv great work. please keep up with it

**Review by ecnracr — APPROVED** [review]

**Comment by ecnracr** [comment]
Wonderful

**Review by Asude-s — APPROVED** [review]

**Review by ZehraAkan — APPROVED** [review]

**Comment by rnkaya** [comment]
Welldone

**Pull request merged**
